name: Dev Container Build and Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Dev Container
      uses: devcontainers/ci@v0.3
      with:
        configFile: .devcontainer/devcontainer.json

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar git

    - name: Download xp-kbt archive
      run: |
        KBT_VERSION="27.0.78"
        KBT_URL="https://github.com/vxcontrol/xp-kbt/releases/download/${KBT_VERSION}/kbt.${KBT_VERSION}-linux.tar.gz"
        wget $KBT_URL -O /home/runner/xp-kbt.tar.gz

    - name: Extract xp-kbt
      run: |
        mkdir -p /home/runner/xp-kbt
        tar -xzvf /home/runner/xp-kbt.tar.gz -C /home/runner/xp-kbt

    - name: List files in extracted directory
      run: |
        ls -l /home/runner
             
    - name: Create required directories
      run: |
        mkdir -p /home/runner/xp-kbt/Temp/eXtractionAndProcessing/output/packages

    - name: download repository
      run: |
        git clone https://github.com/Security-Experts-Community/open-xp-rules.git /home/runner/xp-kbt/open-xp-rules

    - name: set conf
      run: |
        curl https://pastebin.com/raw/AEyV0Cgn > siemj.conf

    - name: Corr rule test
      run: |
        /home/runner/xp-kbt/extra-tools/siemj/siemj -c siemj.conf main