name: Test DevContainer Setup

on:
    workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Dev Container
      uses: devcontainers/ci@v0.3
      with:
        configFile: .devcontainer/devcontainer.json

    - name: Verify DevContainer Setup
      run: "wget https://github.com/vxcontrol/xp-kbt/releases/download/27.0.78/kbt.27.0.78-linux.tar.gz -O /home/vscode/xp-kbt.zip && unzip -o /home/runner/xp-kbt.zip -d /home/runner/xp-kbt" # This prints "Hello, World!" inside the DevContainer