name: Test DevContainer Setup

on:
    workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Dev Container
      uses: devcontainers/ci@v0.3
      with:
        configFile: .devcontainer/devcontainer.json

    - name: Verify DevContainer Setup
      run: "wget $(curl -s https://api.github.com/repos/vxcontrol/xp-kbt/releases/latest | jq -r '.assets[] | select(.name | contains(\"debian\")).browser_download_url') -O /home/vscode/xp-kbt.zip && unzip -o /home/vscode/xp-kbt.zip -d /home/vscode/xp-kbt" # This prints "Hello, World!" inside the DevContainer