name: Test DevContainer Setup

on:
    workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Dev Container
      uses: devcontainers/ci@v0.3
      with:
        configFile: .devcontainer/devcontainer.json

    - name: Verify DevContainer Setup
      run: "pwd" # This prints "Hello, World!" inside the DevContainer